In [2]:
import numpy as np

**Внимание** Во всех заданиях данной работы **запрещено** обращаться к массивам поэлементно и использовать циклы языка Python

**Задание 1.** Напишите функцию, принимающую два массива произвольных размерностей и возвращающую True тогда и только тогда, когда эти два массива поэлементно равны

In [ ]:
from numpy.lib import c_
def task1(x, y):
    return np.array_equal(x, y)

a = np.arange(6).reshape(2, 3)
b = np.array([[0, 1, 2], [3, 4, 5]])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.arange(6)
print(task1(a, b))
print(task1(a, c))
print(task1(a, d))

True
False
False


**Задание 2.** Напишите функцию, которая принимает на вход двумерный массив (это условие можно не проверять), и возврщает массив, в котором каждый элемент исходного массива поделен на сумму модулей элементов его строки.

Например,
для массива
$$
\left(\begin{array}{cc}
    1 & - 1 \\
    2 & 4
\end{array}\right)
$$ должен быть возвращен массив
$$
\left(\begin{array}{cc}
    \frac{1}{2} & -\frac{1}{2} \\
    \frac{1}{3} & -\frac{2}{3}
\end{array}\right)
$$

In [12]:
def task2(x):
    sum_rows = np.sum(abs(x), axis = 1, keepdims=True)
    return(x/sum_rows)

arr = np.array([[1, -1], [2, 4]])
print(task2(arr))

[[ 0.5        -0.5       ]
 [ 0.33333333  0.66666667]]


**Задание 3** Напишите функцию, которая принимает на вход одномреный массив и возвращает матрицу Вандермонда для элемментов этого массива.
Напомним, что матрицей Вандермонда для элементов $(x_1, x_2, \ldots, x_n)$ называется квадратная матрица порядка $n$, имеющая следующий вид
$$
\left(\begin{array}{ccccc}
1 & x_1 & x_1^2 & \ldots  & x_1^{n - 1} \\
1 & x_2 & x_2^2 & \ldots  & x_2^{n - 1} \\
1 & x_3 & x_3^2 & \ldots  & x_3^{n - 1} \\
& & \ldots & & \\
1 & x_n & x_n^2 & \ldots  & x_n^{n - 1} \\
\end{array}
\right)
$$

*Важно*: в этом задании запрещено использовать встроенную функцию `np.vander`. И код из нее тоже не надо копировать и даже творчески переписывать не стоит, для решения достаточно функций, показанных на семинаре

In [31]:
def task3(elements):
    assert len(elements.shape) == 1, "Wrong array format"
    powers = np.arange(len(elements))
    return elements.reshape(-1,1)**powers

arr = np.array([1, 2, 3, 4])
print(task3(arr))

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


**Задание 4.** Напишите функцию, которая принимает на вход массив и возвращает новый массив, который получен из аргмента заменой всех отрицательных элементов на среднее значение всех положительных элементов исходного массива

In [19]:
def task4(ar):
    positive = ar>=0
    ar[~positive] = np.mean(ar[positive])
    return ar

a = np.array([[-4, -1, 2], [3, 4, -5]])
print(task4(a))

[[3 3 2]
 [3 4 3]]
